// Fix generated by Groq Llama 3.3 70B for src/app/api/checkout/route.ts
import { NextResponse } from 'next/server';

export async function POST(req: Request) {
  try {
    const body = await req.json();

    if (!body.customer || !body.customer.address) {
      throw new Error('Customer address is missing');
    }

    c...