// Fix generated by Groq Llama 3.3 70B for src/app/api/inventory/route.ts
import { NextResponse } from 'next/server';

export async function POST(req: Request) {
  try {
    const body = await req.json();

    if (!body || !body.product) {
      throw new Error('Invalid request body: body or body.product is null');
    }

...