// Fix generated by Groq Llama 3.3 70B for src/app/api/discount/route.ts
import { NextResponse } from 'next/server';

export async function POST(req: Request) {
  try {
    const body = await req.json();

    // Use safe optional chaining to avoid TypeError
    const firstItemPrice = body?.items?.[0]?.price || 0;
    cons...