// Fix generated by Groq Llama 3.3 70B for src/app/api/user/profile/route.ts
import { NextResponse } from 'next/server';

export async function POST(req: Request) {
  try {
    const body = await req.json();

    const email = body?.user?.email || 'UNKNOWN';
    const role = body?.user?.role || 'UNKNOWN';

    return NextResp...